AWSTemplateFormatVersion: '2010-09-09'
Description: 'TruthByte DynamoDB Tables'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Resources:
  QuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-questions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

  # Separate table for tag indexing to support multiple tags per question
  QuestionTagsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-question-tags
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tag
          AttributeType: S
        - AttributeName: question_id
          AttributeType: S
      KeySchema:
        - AttributeName: tag
          KeyType: HASH
        - AttributeName: question_id
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

  SubmittedQuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-submitted-questions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

  AnswersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-answers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: question_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: question_id
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: ip_hash
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ip-hash-index
          KeySchema:
            - AttributeName: ip_hash
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

Outputs:
  QuestionsTableName:
    Description: Name of the questions table
    Value: !Ref QuestionsTable
    Export:
      Name: !Sub ${Environment}-QuestionsTableName

  QuestionTagsTableName:
    Description: Name of the question tags table
    Value: !Ref QuestionTagsTable
    Export:
      Name: !Sub ${Environment}-QuestionTagsTableName

  SubmittedQuestionsTableName:
    Description: Name of the submitted questions table
    Value: !Ref SubmittedQuestionsTable
    Export:
      Name: !Sub ${Environment}-SubmittedQuestionsTableName

  AnswersTableName:
    Description: Name of the answers table
    Value: !Ref AnswersTable
    Export:
      Name: !Sub ${Environment}-AnswersTableName

  SessionsTableName:
    Description: Name of the sessions table
    Value: !Ref SessionsTable
    Export:
      Name: !Sub ${Environment}-SessionsTableName

  QuestionsTableArn:
    Description: ARN of the questions table
    Value: !GetAtt QuestionsTable.Arn
    Export:
      Name: !Sub ${Environment}-QuestionsTableArn

  SubmittedQuestionsTableArn:
    Description: ARN of the submitted questions table
    Value: !GetAtt SubmittedQuestionsTable.Arn
    Export:
      Name: !Sub ${Environment}-SubmittedQuestionsTableArn

  AnswersTableArn:
    Description: ARN of the answers table
    Value: !GetAtt AnswersTable.Arn
    Export:
      Name: !Sub ${Environment}-AnswersTableArn

  SessionsTableArn:
    Description: ARN of the sessions table
    Value: !GetAtt SessionsTable.Arn
    Export:
      Name: !Sub ${Environment}-SessionsTableArn

  QuestionTagsTableArn:
    Description: ARN of the question tags table
    Value: !GetAtt QuestionTagsTable.Arn
    Export:
      Name: !Sub ${Environment}-QuestionTagsTableArn 