AWSTemplateFormatVersion: '2010-09-09'
Description: 'TruthByte DynamoDB Tables'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Resources:
  QuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-questions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

  # Separate table for category indexing to support multiple categories per question
  QuestionCategoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-question-categories
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: category
          AttributeType: S
        - AttributeName: question_id
          AttributeType: S
      KeySchema:
        - AttributeName: category
          KeyType: HASH
        - AttributeName: question_id
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

  # New table for category metadata (name, description, question count, etc.)
  CategoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-categories
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: category_id
          AttributeType: S
      KeySchema:
        - AttributeName: category_id
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

  SubmittedQuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-submitted-questions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: author
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: submitted_at
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: author-index
          KeySchema:
            - AttributeName: author
              KeyType: HASH
            - AttributeName: submitted_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: submitted_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

  AnswersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-answers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: question_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: question_id
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: ip_hash
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ip-hash-index
          KeySchema:
            - AttributeName: ip_hash
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

Outputs:
  QuestionsTableName:
    Description: Name of the questions table
    Value: !Ref QuestionsTable
    Export:
      Name: !Sub ${Environment}-QuestionsTableName

  QuestionCategoriesTableName:
    Description: Name of the question categories table
    Value: !Ref QuestionCategoriesTable
    Export:
      Name: !Sub ${Environment}-QuestionCategoriesTableName

  SubmittedQuestionsTableName:
    Description: Name of the submitted questions table
    Value: !Ref SubmittedQuestionsTable
    Export:
      Name: !Sub ${Environment}-SubmittedQuestionsTableName

  AnswersTableName:
    Description: Name of the answers table
    Value: !Ref AnswersTable
    Export:
      Name: !Sub ${Environment}-AnswersTableName

  SessionsTableName:
    Description: Name of the sessions table
    Value: !Ref SessionsTable
    Export:
      Name: !Sub ${Environment}-SessionsTableName

  UsersTableName:
    Description: Name of the users table
    Value: !Ref UsersTable
    Export:
      Name: !Sub ${Environment}-UsersTableName

  QuestionsTableArn:
    Description: ARN of the questions table
    Value: !GetAtt QuestionsTable.Arn
    Export:
      Name: !Sub ${Environment}-QuestionsTableArn

  SubmittedQuestionsTableArn:
    Description: ARN of the submitted questions table
    Value: !GetAtt SubmittedQuestionsTable.Arn
    Export:
      Name: !Sub ${Environment}-SubmittedQuestionsTableArn

  AnswersTableArn:
    Description: ARN of the answers table
    Value: !GetAtt AnswersTable.Arn
    Export:
      Name: !Sub ${Environment}-AnswersTableArn

  SessionsTableArn:
    Description: ARN of the sessions table
    Value: !GetAtt SessionsTable.Arn
    Export:
      Name: !Sub ${Environment}-SessionsTableArn

  UsersTableArn:
    Description: ARN of the users table
    Value: !GetAtt UsersTable.Arn
    Export:
      Name: !Sub ${Environment}-UsersTableArn

  QuestionCategoriesTableArn:
    Description: ARN of the question categories table
    Value: !GetAtt QuestionCategoriesTable.Arn
    Export:
      Name: !Sub ${Environment}-QuestionCategoriesTableArn

  CategoriesTableArn:
    Description: ARN of the categories table
    Value: !GetAtt CategoriesTable.Arn
    Export:
      Name: !Sub ${Environment}-CategoriesTableArn

  CategoriesTableName:
    Description: Name of the categories table
    Value: !Ref CategoriesTable
    Export:
      Name: !Sub ${Environment}-CategoriesTableName 