AWSTemplateFormatVersion: '2010-09-09'
Description: 'TruthByte DynamoDB Tables'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Resources:
  QuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-questions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

  AnswersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-answers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-truthbyte-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: ip_hash
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ip-hash-index
          KeySchema:
            - AttributeName: ip_hash
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TruthByte

Outputs:
  QuestionsTableName:
    Description: Name of the questions table
    Value: !Ref QuestionsTable
    Export:
      Name: !Sub ${Environment}-QuestionsTableName

  AnswersTableName:
    Description: Name of the answers table
    Value: !Ref AnswersTable
    Export:
      Name: !Sub ${Environment}-AnswersTableName

  SessionsTableName:
    Description: Name of the sessions table
    Value: !Ref SessionsTable
    Export:
      Name: !Sub ${Environment}-SessionsTableName

  QuestionsTableArn:
    Description: ARN of the questions table
    Value: !GetAtt QuestionsTable.Arn
    Export:
      Name: !Sub ${Environment}-QuestionsTableArn

  AnswersTableArn:
    Description: ARN of the answers table
    Value: !GetAtt AnswersTable.Arn
    Export:
      Name: !Sub ${Environment}-AnswersTableArn

  SessionsTableArn:
    Description: ARN of the sessions table
    Value: !GetAtt SessionsTable.Arn
    Export:
      Name: !Sub ${Environment}-SessionsTableArn 