AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for TruthByte frontend static site'

Parameters:
  BucketName:
    Type: String
    Default: truthbyte.voidtalker.com
    Description: S3 bucket name for the static site
  CloudFrontOAI:
    Type: String
    Description: CloudFront Origin Access Identity (OAI) canonical user ID (get this from your CloudFront console)

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false  # Change to true if you want to block public access to the bucket
        IgnorePublicAcls: true
        RestrictPublicBuckets: false  # Change to true if you want to block public access to the bucket

  # Policy to allow CloudFront OAI to read from the bucket
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !Ref CloudFrontOAI
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${FrontendBucket}/*'

Outputs:
  WebsiteURL:
    Description: 'URL for static website hosting'
    Value: !GetAtt FrontendBucket.WebsiteURL
  BucketName:
    Description: 'S3 bucket name'
    Value: !Ref FrontendBucket 