AWSTemplateFormatVersion: '2010-09-09'
Description: 'TruthByte Lambda Functions'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name
  ArtifactBucket:
    Type: String
    Description: S3 bucket for Lambda deployment packages
  JwtSecret:
    Type: String
    NoEcho: true
    Description: JWT secret key for token signing and verification

Resources:
  FetchQuestionsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Environment}-truthbyte-fetch-questions
      Handler: fetch_questions.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: fetch-questions.zip
      Runtime: python3.13
      Timeout: 30
      MemorySize: 256
      ReservedConcurrentExecutions: 2
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: INFO
          JWT_SECRET: !Ref JwtSecret
          QUESTIONS_TABLE_NAME: 
            Fn::ImportValue: 
              Fn::Sub: ${Environment}-QuestionsTableName
          QUESTION_TAGS_TABLE_NAME: 
            Fn::ImportValue: 
              Fn::Sub: ${Environment}-QuestionTagsTableName

  SubmitAnswerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Environment}-truthbyte-submit-answers
      Handler: submit_answers.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: submit-answers.zip
      Runtime: python3.13
      Timeout: 30
      MemorySize: 256
      ReservedConcurrentExecutions: 2
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: INFO
          JWT_SECRET: !Ref JwtSecret
          ANSWERS_TABLE_NAME: 
            Fn::ImportValue: 
              Fn::Sub: ${Environment}-AnswersTableName

  ProposeQuestionFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Environment}-truthbyte-propose-question
      Handler: propose_question.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: propose-question.zip
      Runtime: python3.13
      Timeout: 30
      MemorySize: 256
      ReservedConcurrentExecutions: 2
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: INFO
          JWT_SECRET: !Ref JwtSecret
          SUBMITTED_QUESTIONS_TABLE_NAME: 
            Fn::ImportValue: 
              Fn::Sub: ${Environment}-SubmittedQuestionsTableName

  GetTokenFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Environment}-truthbyte-get-token
      Handler: get_token.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: get-token.zip
      Runtime: python3.13
      Timeout: 30
      MemorySize: 256
      ReservedConcurrentExecutions: 2
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: INFO
          JWT_SECRET: !Ref JwtSecret

  AuthPingFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Environment}-truthbyte-auth-ping
      Handler: auth_ping.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: auth-ping.zip
      Runtime: python3.13
      Timeout: 30
      MemorySize: 256
      ReservedConcurrentExecutions: 2
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: INFO
          JWT_SECRET: !Ref JwtSecret

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - Fn::ImportValue: 
                      Fn::Sub: ${Environment}-QuestionsTableArn
                  - Fn::ImportValue: 
                      Fn::Sub: ${Environment}-QuestionTagsTableArn
                  - Fn::ImportValue: 
                      Fn::Sub: ${Environment}-SubmittedQuestionsTableArn
                  - Fn::ImportValue: 
                      Fn::Sub: ${Environment}-AnswersTableArn
                  - Fn::ImportValue: 
                      Fn::Sub: ${Environment}-SessionsTableArn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

Outputs:
  FetchQuestionsFunctionArn:
    Description: ARN of the fetch questions Lambda function
    Value: !GetAtt FetchQuestionsFunction.Arn
    Export:
      Name: !Sub ${Environment}-FetchQuestionsFunctionArn

  SubmitAnswerFunctionArn:
    Description: ARN of the submit answer Lambda function
    Value: !GetAtt SubmitAnswerFunction.Arn
    Export:
      Name: !Sub ${Environment}-SubmitAnswerFunctionArn

  ProposeQuestionFunctionArn:
    Description: ARN of the propose question Lambda function
    Value: !GetAtt ProposeQuestionFunction.Arn
    Export:
      Name: !Sub ${Environment}-ProposeQuestionFunctionArn

  GetTokenFunctionArn:
    Description: ARN of the get token Lambda function
    Value: !GetAtt GetTokenFunction.Arn
    Export:
      Name: !Sub ${Environment}-GetTokenFunctionArn

  AuthPingFunctionArn:
    Description: ARN of the auth ping Lambda function
    Value: !GetAtt AuthPingFunction.Arn
    Export:
      Name: !Sub ${Environment}-AuthPingFunctionArn 